package com.dttmap.thank.utils;

import com.dttmap.thank.bean.AddressBean;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Administrator on 2018/8/22/022.
 */

public class DataUtil {

 
public static List<AddressBean> addressList = new ArrayList<>();
//    static {
////        9月经销商走访信息登记表
////        序号		客户		区域		业务员		具体地址
//addressList.add(new AddressBean(1,"周兴龙","市区一部中心一区","孙曦哲	","株洲市芦淞区建设南路108号家润多一楼内场145号毅龙手机连锁"));
//addressList.add(new AddressBean(2,"株洲龙毅科技有限公司","市区一部中心一区","孙曦哲	","株洲市芦淞区建设南路108号家润多一楼内场145号毅龙手机连锁"));
//addressList.add(new AddressBean(3,"株洲市芦淞区星天通信店","市区一部中心一区","孙曦哲	","株洲市芦淞区建设南路108号家润多一楼蓝天专卖（美佳市场收银台旁）"));
//addressList.add(new AddressBean(4,"株洲市芦淞区星天通信店（家润多2店）","市区一部中心一区","孙曦哲	","株洲市芦淞区建设南路108号家润多一楼蓝天专卖（美佳市场收银台旁）"));
//addressList.add(new AddressBean(5,"包银芳","市区一部中心一区","孙曦哲	","株洲市芦淞区建设南路108号家润多一楼家润多美佳手机城A22柜台"));
//
//addressList.add(new AddressBean(6,"株洲国联通信实业有限责任公司","市区一部中心五区","王睿","湖南省株洲市芦淞区中心广场家润多美佳手机广场C08"));
//addressList.add(new AddressBean(7,"芦淞区逢缘通讯行","市区一部中心五区","王睿","湖南省株洲市芦淞区中心广场家润多1楼手机卖场移动大厅门口"));
//addressList.add(new AddressBean(8,"家润多掌中科技","市区一部中心五区","王睿","湖南省株洲市芦淞区中心广场家润多1楼手机卖场133号"));
//addressList.add(new AddressBean(9,"郭静","市区一部中心五区","王睿	","湖南省株洲市芦淞区中心广场家润多1楼手机卖场京升仓库"));
//addressList.add(new AddressBean(10,"京升实业有限公司","市区一部中心五区","王睿	","湖南省株洲市芦淞区中心广场家润多1楼手机卖场京升仓库"));
//addressList.add(new AddressBean(11,"彭忠","市区一部中心五区" ,"王睿	","株洲市芦淞区中心广场家润多美佳手机城C09柜台"));
//addressList.add(new AddressBean(12,"陈鸿","市区一部中心五区"   ,"王睿	","株洲市芦淞区中心广场家润多美佳手机城C03柜台"));
//addressList.add(new AddressBean(13,"芦淞区栗子数码产品商行","市区一部中心五区"       ,"王睿	","湖南省株洲市芦淞区中心广场家润多一楼美佳仓库"));
//
//
//addressList.add(new AddressBean(14,"湖南齐欣商务服务有限公司","市区一部中心三区","谭清明	","株洲市芦淞区建设中路29号电信大楼右边上坡尽头二楼"));
//addressList.add(new AddressBean(15,"湖南齐帜通信管理有限公司","市区一部中心三区","谭清明	","株洲市芦淞区建设中路29号电信大楼右边上坡尽头二楼"));
//addressList.add(new AddressBean(16,"芦淞区富讯通讯行（贺家土）","市区一部中心三区","谭清明	","株洲市芦淞区贺嘉路贺家土菜市场门口"));
//addressList.add(new AddressBean(17,"雷小毛","市区一部中心三区","谭清明	","株洲市芦淞区天鹅花园内物业公司门口"));
//addressList.add(new AddressBean(18,"芦淞区速达通讯行","市区一部中心三区","谭清明	","株洲市芦淞区贺嘉路贺家土菜市场二楼"));
//addressList.add(new AddressBean(19,"杨波","市区一部中心三区","谭清明	","株洲市芦淞区贺嘉土建设中路500号中国联通"));
//addressList.add(new AddressBean(20,"芦淞区津诚通讯行","市区一部中心三区","谭清明	","株洲市芦淞区文化园贺家土小学对面中国移动"));
//addressList.add(new AddressBean(21,"芦淞区捷讯手机经营部","市区一部中心三区","谭清明	","株洲市芦淞区建设中路688号全网通4G手机城"));
//addressList.add(new AddressBean(22,"株洲市隆辉通讯部","市区一部中心三区","谭清明	","株洲市芦淞区人民中路486号"));
//addressList.add(new AddressBean(23,"TZ株洲A双银vivo专卖店","市区一部中心三区","谭清明	","株洲市芦淞区双银大厦一楼168号"));
//addressList.add(new AddressBean(24,"芦淞区凌天通讯设备经营部","市区一部中心三区","谭清明	","株洲市芦淞区七一路110号凌天通讯"));
//addressList.add(new AddressBean(25,"株洲银信科技发展有限公司","市区一部中心三区","谭清明	","株洲市双银大厦一楼168号"));
//addressList.add(new AddressBean(26,"芦淞区长风通信商行","市区一部中心三区","谭清明	","株洲市芦淞区电信大楼邮政银行左边vivo门头"));
//addressList.add(new AddressBean(27,"龙武","市区一部中心三区","谭清明	","株洲市双银大厦一楼168号"));
//addressList.add(new AddressBean(28,"汤秀华","市区一部中心三区","谭清明	","株洲市芦淞区建设南路老电信大楼"));
//addressList.add(new AddressBean(29,"钟兰","市区一部中心三区","谭清明	","株洲市芦淞区建设南路老电信大楼"));
//addressList.add(new AddressBean(30,"株洲德聚通用有限公司","市区一部中心三区","谭清明	","体育路广冶大厦1楼"));
//addressList.add(new AddressBean(31,"株洲市三合科技发展有限公司","市区一部中心三区","谭清明	","株洲市芦淞区建设中路11号中国联通"));
//addressList.add(new AddressBean(32,"贰柒通讯","市区一部中心六区","余文景	","湖南省株洲市芦淞区中心广场家润多一楼111号"));
//addressList.add(new AddressBean(33,"芦淞区人天通讯行","市区一部中心六区","余文景	","株洲市芦淞区家润多一楼148号迷你数码"));
//addressList.add(new AddressBean(34,"株洲瑞鑫数码产品有限公司","市区一部中心六区","余文景	","株洲市芦淞区中心广场家润多1楼B12"));
//addressList.add(new AddressBean(35,"刘晒云","市区一部中心六区","余文景	","株洲市芦淞区家润多一楼A12"));
//addressList.add(new AddressBean(36,"李腾飞","市区一部中心六区","余文景	","株洲市芦淞区中心广场家润多1楼B09"));
//addressList.add(new AddressBean(37,"芦淞区卿卿电器行","市区一部中心六区","余文景	","株洲市芦淞区家润多一楼A12"));
//addressList.add(new AddressBean(38,"湖南中讯通电子科技有限公司","市区一部中心六区","余文景	","株洲市芦淞区中心广场家润多1楼建设南路108号"));
//addressList.add(new AddressBean(39,"株洲百货股份有限公司","市区一部中心六区","余文景	","株洲市芦淞区中心广场株洲百货大楼2楼"));
//addressList.add(new AddressBean(40,"芦淞区乐加通讯","市区一部中心六区","余文景	","株洲市芦淞区建设中路8号电信大楼邮政二楼"));
//addressList.add(new AddressBean(41,"湖南中讯通电子科技有限公司(新)","市区一部中心六区","余文景	","#N/A"));
//addressList.add(new AddressBean(42,"芦淞区鸿瑞通讯行","市区一部中心二区","王睿	","株洲市芦淞区中心广场家润多联通4G手机城芦淞鸿瑞柜台"));
//addressList.add(new AddressBean(43,"芦淞区万顺通讯行","市区一部中心二区","王睿	","株洲市芦淞区中心广场家润多联通4G手机城万顺柜台"));
//addressList.add(new AddressBean(44,"芦淞区全讯通信产品商行","市区一部中心二区","王睿	","株洲市芦淞区中心广场家润多联通4G手机城D区域4节柜台全讯柜台"));
//addressList.add(new AddressBean(45,"姚玲芝","市区一部中心二区","王睿	","株洲市芦淞区中心广场家润多联通4G手机城恒达柜台"));
//addressList.add(new AddressBean(46,"芦淞区佳家通讯行","市区一部中心二区","王睿	","株洲市芦淞区中心广场家润多联通4G手机城佳家柜台"));
//addressList.add(new AddressBean(47,"周端","市区一部中心二区","王睿	","株洲市芦淞区中心广场家润多联通4G手机城傲天柜台"));
//addressList.add(new AddressBean(48,"天元区魔特电讯电信业务代办点","市区一部西一区","易健	","株洲市天元区神龙城城市星座沃尔玛超市入口魔特电讯手机店"));
//addressList.add(new AddressBean(49,"天元区鼎盛手机店","市区一部西一区","易健	","株洲市天元区河西四桥桥头鼎盛手机专卖店(大金厨厅内)"));
//addressList.add(new AddressBean(50,"天元区滨江沃店","市区一部西一区","易健	","株洲市天元区长江南路634号(联通店)"));
//addressList.add(new AddressBean(51,"天元区尚智电讯行","市区一部西一区","易健	","#N/A"));
//addressList.add(new AddressBean(52,"湖南新联盛商贸有限公司","市区一部西一区","易健	","株洲市天元区金茂尚都A座2203"));
//addressList.add(new AddressBean(53,"戴奕","市区一部西一区","易健	","株洲市天元区金茂尚都A座2203"));
//addressList.add(new AddressBean(54,"天元区鹏泰电信专营店","市区一部西一区","易健	","株洲市天元区紫竹茗园3栋103号门面中国电信专营店"));
//addressList.add(new AddressBean(55,"天元区珠江花园中球移动业务代办点","市区一部西一区","易健	","株洲市天元区珠江南路天台小区12号门面"));
//addressList.add(new AddressBean(56,"株洲市天元区马家河镇王家坪一通通讯经营部","市区一部西一区","易健	","株洲市天元区王家坪街50号中国联通马家河沃店"));
//addressList.add(new AddressBean(57,"天元区肆壹陆移动业务代办点","市区一部西一区","易健	","株洲市天元区416队临街门面南12号中国移动店"));
//addressList.add(new AddressBean(58,"天元区炳恒通讯点","市区一部西一区","易健	","株洲市天元区王家坪街道51号门面炳恒通讯店"));
//addressList.add(new AddressBean(59,"株洲市天元区马家河镇移动金龙指定代理店","市区一部西一区","易健	","株洲市天元区群丰镇妙泉社区对面中国电信"));
//addressList.add(new AddressBean(60,"株洲市天元区栗雨王家坪电信业务代办点","市区一部西一区","易健	","湖南省株洲市天元区马家河镇王家坪街上33号（中国电信）门面"));
//addressList.add(new AddressBean(61,"天元区湘江移动通讯行","市区一部西一区","易健	","株洲市天元区衡山中路湘江名都中国移动手机专卖店"));
//addressList.add(new AddressBean(62,"株洲市天元区群丰镇长岭社区建平移动专营店","市区一部西一区","易健	","株洲市天元区群丰镇长岭社区群丰移动指定专营店"));
//addressList.add(new AddressBean(63,"株洲市天元区群丰镇治国经营部","市区一部西一区","易健	","株洲市天元区群丰镇长岭街十字路口联通移动专营店"));
//addressList.add(new AddressBean(64,"炎帝广场金座电信营业厅","市区一部西二区 ","何强国	","株洲市天元区炎帝广场金座电信营业厅"));
//addressList.add(new AddressBean(65,"天元区佳和通讯柜台外包厅","市区一部西二区 ","何强国	","株洲市天元区联通自营厅"));
//addressList.add(new AddressBean(66,"湖南三鼎通信科技有限公司","市区一部西二区 ","何强国	","株洲市天元区圆方路联通自营厅"));
//addressList.add(new AddressBean(67,"天元区鸿瑞通讯行","市区一部西二区 ","何强国	","株洲市天元区圆方路"));
//addressList.add(new AddressBean(68,"天元区一网通信店","市区一部西二区 ","何强国	","株洲市天元区联谊怡沁园6栋2号"));
//addressList.add(new AddressBean(69,"天元区飞意电信营业厅","市区一部西二区 ","何强国	","株洲市天元区香山美境22栋101号门面"));
//addressList.add(new AddressBean(70,"天元区潘霞宽带电视手机服务","市区一部西二区 ","何强国	","株洲市天元区栗雨工业园明月路蓝筹公寓1栋114号"));
//addressList.add(new AddressBean(71,"天元区高塘联通营业厅","市区一部西二区 ","何强国	","株洲市天元区高塘小区23栋3号中国移动"));
//addressList.add(new AddressBean(72,"天元区翠谷城电信代办点","市区一部西二区 ","何强国	","株洲市天元区翠谷城电信营业厅894号门面"));
//addressList.add(new AddressBean(73,"株洲市精诚电子科技服务部","市区一部西二区 ","何强国	","株洲市天元区栗雨株百二楼"));
//addressList.add(new AddressBean(74,"天元区天美联通店","市区一部西二区 ","何强国	","株洲市天元区庐山路庐山恋12栋103号联通"));
//addressList.add(new AddressBean(75,"株洲市天元区湘水栗园小区栗园邮政代办点","市区一部西二区 ","何强国	","株洲市天元区湘水栗园13栋102号中国移动"));
//addressList.add(new AddressBean(76,"天元区海盛中国电信美的城经营部","市区一部西二区 ","何强国	","株洲市天元区美的城15栋118号"));
//addressList.add(new AddressBean(77,"石峰区柏松工贸通讯店","市区一部西二区 ","何强国	","株洲市天元区栗雨美的城时代广场联通营业厅"));
//addressList.add(new AddressBean(78,"株洲市天元区马家河镇高塘移动通信指定专营店","市区一部西二区 ","何强国	","株洲市天元区高塘小区25栋4号门面"));
//addressList.add(new AddressBean(79,"天元区美的城美妙移动业务代办点","市区一部西二区 ","何强国	","株洲市天元隆兴路156号栗雨湖B区18栋121、113号"));
//addressList.add(new AddressBean(80,"天元区零点通讯庐山一号服务部","市区一部西二区 ","何强国	","株洲市天元区庐山路188号"));
//addressList.add(new AddressBean(81,"天元区鸿信手机城","市区一部西二区 ","何强国	","株洲市天元区圆方路口"));
//addressList.add(new AddressBean(82,"天元区恒大天翼电信专营店","市区一部西二区 ","何强国	","天元区湘山路天泰家园106号"));
//addressList.add(new AddressBean(83,"天元区星辰通讯","市区一部西二区 ","何强国	","#N/A"));
//addressList.add(new AddressBean(84,"苏建强","市区一部西二区 ","何强国	","株洲市天元区韶山路花园二村"));
//addressList.add(new AddressBean(85,"尹志斌","市区一部西二区","何强国	","株洲市天元区圆方路联通自营厅"));
//addressList.add(new AddressBean(86,"株洲市领创科技有限公司","市区一部西二区","何强国	","天元区旺城天悦小区"));
//addressList.add(new AddressBean(87,"天元区马家河镇新马联通营业厅","市区一部西二区","何强国	","天元区马家河镇新马社区尚家洲23号"));
//addressList.add(new AddressBean(88,"芦淞区鹰利通讯行","市区三部乡镇区","刘自成	","株洲市芦淞区高科园"));
//addressList.add(new AddressBean(89,"芦淞区讯天游移动营业厅","市区三部乡镇区","刘自成	","株洲市芦淞区白关镇白关广场天宇移动"));
//addressList.add(new AddressBean(90,"株洲县仙井乡陈张公岭指定专营店","市区三部乡镇区","刘自成	","株洲县仙井乡张公岭村邮政银行对面"));
//addressList.add(new AddressBean(91,"刘毅--湖南省株洲市芦淞区姚家坝乡姚家坝村","市区三部乡镇区","刘自成	","湖南省株洲市芦淞区姚家坝乡电信手机店"));
//addressList.add(new AddressBean(92,"芦淞区英英全网通手机卖场","市区三部乡镇区","刘自成	","株洲市芦淞区白关镇邮政银行旁电信手机店"));
//addressList.add(new AddressBean(93,"株洲县渌口镇成真通讯连锁精品店","市区三部乡镇区","刘自成	","株洲县渌口镇烟草局门面成真移动"));
//addressList.add(new AddressBean(94,"三鸿手机店","市区三部乡镇区","刘自成	","株洲市天元区三门镇街上移动"));
//addressList.add(new AddressBean(95,"株洲县古岳峰移动指定专营店","市区三部乡镇区","刘自成	","株洲县古岳峰镇汤圆坳移动"));
//addressList.add(new AddressBean(96,"株洲市天元区雷打石镇戈再移动代办点","市区三部乡镇区","刘自成	","株洲市天元区雷打石镇伞铺戈再移动"));
//addressList.add(new AddressBean(97,"红红手机卖场","市区三部乡镇区","刘自成	","湖南省株洲市天元区雷打石镇伞铺街上"));
//addressList.add(new AddressBean(98,"天天来移动","市区三部乡镇区","刘自成	","湖南省株洲市天元区三门镇街上邮政银行对面"));
//addressList.add(new AddressBean(99,"株洲县古岳峰镇罗馗电信专营店","市区三部乡镇区","刘自成	","株洲县古岳峰镇街上"));
//addressList.add(new AddressBean(100,"马玲","市区三部乡镇区","刘自成	","湖南省株洲市天元区三门街上中国电信"));
//addressList.add(new AddressBean(101,"冯良","市区三部乡镇区","刘自成	","湖南省株洲市雷打石镇伞铺街上"));
//addressList.add(new AddressBean(102,"天元区三门镇全网通手机专卖场","市区三部乡镇区","刘自成	","湖南省株洲市天元区三门街上全网痛手机卖场"));
//addressList.add(new AddressBean(103,"唐海江","市区三部乡镇区","刘自成	","株洲市天元区雷打石街上瓷厂对面"));
//addressList.add(new AddressBean(104,"株洲县堂乡市黄竹村鹏程移动业务代办专营店","市区三部乡镇区","刘自成	","湖南省株洲县龙船镇堂市黄竹村华新水泥厂对面"));
//addressList.add(new AddressBean(105,"株洲市天元区雷打石镇苏文辉电信代办点","市区三部乡镇区","刘自成	","湖南省株洲市天元区雷打石镇伞铺街"));
//addressList.add(new AddressBean(106,"株洲市天元区雷打石镇伞铺光强营业厅","市区三部乡镇区","刘自成	","雷打石镇伞铺街上"));
//addressList.add(new AddressBean(107,"天元区雷打石镇移动通讯诚信营业所","市区三部乡镇区","刘自成	","雷打石镇街上"));
//addressList.add(new AddressBean(108,"株洲市天元区雷打石镇建强黄亮移动代办店","市区三部乡镇区","刘自成	","雷打石建强村"));
//addressList.add(new AddressBean(109,"株洲县渌口镇黎韶路口移动建民指定专营店","市区三部乡镇区","刘自成	","湖南省株洲县渌口镇黎韶路口移动建民指定专营店"));
//addressList.add(new AddressBean(110,"株洲县淦田镇嘉嘉移动通信专营点","市区三部乡镇区","刘自成	","湖南省株洲县淦田镇街上"));
//addressList.add(new AddressBean(111,"株洲县砖桥福祥移动代办店","市区三部乡镇区","刘自成	","株洲县砖桥乡街上"));
//addressList.add(new AddressBean(112,"株洲县凎田朝辉联通委办点","市区三部乡镇区","刘自成	","湖南省株洲县淦田镇街上"));
//addressList.add(new AddressBean(113,"曾金平","市区三部乡镇区","刘自成	","湖南省株洲县淦田镇街上"));
//addressList.add(new AddressBean(114,"唐磊","市区三部乡镇区","刘自成	","湖南省株洲县南洲镇江边村加油站对面"));
//addressList.add(new AddressBean(115,"株洲县仙井王竹联通营业厅","市区三部乡镇区","刘自成	","株洲县仙井乡凳头村庙冲组"));
//addressList.add(new AddressBean(116,"株洲县朱亭镇黄龙电信代办点","市区三部乡镇区","刘自成	","株洲县朱亭镇黄龙街上电信营业厅"));
//addressList.add(new AddressBean(117,"株洲县南州刘平手机店","市区三部乡镇区","刘自成	","株洲市株洲县烟草局门面成真移动店"));
//addressList.add(new AddressBean(118,"株洲县渌口镇耀华科技服务部漉浦店","市区三部县城区","袁孜	","株洲县渌口镇漉浦路公安局对面移动营业厅"));
//addressList.add(new AddressBean(119,"株洲县向阳手机店","市区三部县城区","袁孜	","株洲县渌口镇向阳南路电信营业厅"));
//addressList.add(new AddressBean(120,"株洲县渌口镇黄金路旭勇通信经营部","市区三部县城区","袁孜	","株洲县渌口镇黄金西路移动手机店"));
//addressList.add(new AddressBean(121,"株洲县渌口镇杨繁商行","市区三部县城区","袁孜	","株洲县渌口火车站联通"));
//addressList.add(new AddressBean(122,"株洲县远行通讯经营部","市区三部县城区","袁孜	","株洲县渌口镇迎宾路6号三星售后远行通讯"));
//addressList.add(new AddressBean(123,"株洲县渌口镇鼎德通讯店","市区三部县城区","袁孜	","株洲县渌口镇五中斜对面鼎德通讯"));
//addressList.add(new AddressBean(124,"长沙通程控股股份有限公司株洲县通程电器渌口向阳广场店","市区三部县城区","袁孜	","株洲县渌口镇向阳广场通程电器"));
//addressList.add(new AddressBean(125,"株洲县瑞和通讯器材经营部","市区三部县城区","袁孜	","株洲县渌口镇瑞和广场瑞和移动店"));
//addressList.add(new AddressBean(126,"株洲县恒瑞移动指定专营店","市区三部县城区","袁孜	","株洲县渌口新汽车站旁恒瑞移动（十字路口）"));
//addressList.add(new AddressBean(127,"株洲县渌口凌云通讯漉浦分店","市区三部县城区","袁孜	","株洲县渌口镇漉浦路烟草局旁联通营业厅"));
//addressList.add(new AddressBean(128,"株洲县渌口镇梅苑路移动代办点","市区三部县城区","袁孜	","株洲县渌口镇梅苑路中国移动（摩托车大市场旁）"));
//addressList.add(new AddressBean(129,"株洲县渌口镇大海通讯专营店","市区三部县城区","袁孜	","株洲县渌口镇中央时代广场D栋105号"));
//addressList.add(new AddressBean(130,"株洲县渌口镇伏波广场手机专卖","市区三部县城区","袁孜	","株洲县渌口镇甘塘坡"));
//addressList.add(new AddressBean(131,"株洲10号(东都店)","市区三部东区","李杰	","株洲市荷塘区红旗广场步步高超市3楼"));
//addressList.add(new AddressBean(132,"步步高商业连锁股份有限公司","市区三部东区","李杰	","株洲市荷塘区步步高超市一楼手机柜"));
//addressList.add(new AddressBean(133,"株洲联盛通信有限责任公司","市区三部东区","李杰	","株洲市天元区天台路金茂尚都B座2016"));
//addressList.add(new AddressBean(134,"吴琼华","市区三部东区","李杰	","株洲市天元区天台路金茂尚都B座2016"));
//addressList.add(new AddressBean(135,"株洲乐语通讯有限公司（东都店）","市区三部东区","李杰	","株洲市荷塘区东都文化广场1026号"));
//addressList.add(new AddressBean(136,"株洲零售","市区三部东区","李杰	","株洲市荷塘区东都文化广场1026号"));
//addressList.add(new AddressBean(137,"荷塘区嘉晖通讯店","市区三部东区","李杰	","株洲市荷塘区新华东路东方花园旁1526号嘉晖通讯手机店"));
//addressList.add(new AddressBean(138,"永乐通讯","市区三部东区","李杰	","株洲市荷塘区红旗广场东都大酒店旁中国移动永乐营业厅"));
//addressList.add(new AddressBean(139,"荷塘区湘宇手机店","市区三部东区","李杰	","红旗路东都大酒店对面"));
//addressList.add(new AddressBean(140,"荷塘区华林腾达通讯行","市区三部城郊三区","夏泉龙	","株洲市荷塘区向阳路东部美的城14栋101门面中国电信营业厅"));
//addressList.add(new AddressBean(141,"荷塘区中移通讯手机店","市区三部城郊三区","夏泉龙	","株洲市荷塘区步步高负一楼"));
//addressList.add(new AddressBean(142,"株洲市荷塘区雯雯手机店","市区三部城郊三区","夏泉龙	","株洲市荷塘区湘运南路百合嘉园9栋14号金钩山移动门面"));
//addressList.add(new AddressBean(143,"株洲市荷塘区鑫伟通信商行","市区三部城郊三区","夏泉龙	","株洲市荷塘区红旗中路中南蔬菜批发市场门口中国移动店"));
//addressList.add(new AddressBean(144,"荷塘区腾逸通信店","市区三部城郊三区","夏泉龙	","株洲市荷塘区升龙路御景龙湾1栋104门面"));
//addressList.add(new AddressBean(145,"株洲市荷塘区中移动锦荷指定专营店","市区三部城郊三区","夏泉龙	","株洲市荷塘区红旗南路锦龙小区23栋中国移动指定专营店"));
//addressList.add(new AddressBean(146,"株洲市荷塘区佳嘉通讯营业厅","市区三部城郊三区","夏泉龙	","株洲市红旗广场新华西路伟大国际B-49号佳嘉移动手机专卖店"));
//addressList.add(new AddressBean(147,"株洲市荷塘区华鑫联合联通代办点","市区三部城郊三区","夏泉龙	","株洲市荷塘区红旗中路湘银商铺1-216,1-217号门面"));
//addressList.add(new AddressBean(148,"石峰区智天手机店","市区三部城郊三区","夏泉龙	","株洲市石峰区田心东门富佳超市对面中国移动智天店"));
//addressList.add(new AddressBean(149,"株洲市石峰区怡园小区移动营业厅","市区三部城郊三区","夏泉龙	","湖南省株洲市石峰区田心北门邮局旁新田心移动营业厅"));
//addressList.add(new AddressBean(150,"株洲市荷塘区兴鸿通讯行","市区三部城郊二区","周炜	","湖南省株洲市荷塘区新华西路84号（荷叶塘对面中国移动鸿信店）"));
//addressList.add(new AddressBean(151,"株洲市荷塘区小凡通讯移动专营店","市区三部城郊二区","周炜	","株洲市荷塘区新华西路532号中国移动手机专卖店"));
//addressList.add(new AddressBean(152,"芦淞区拓和通信行","市区三部城郊二区","周炜	","芦淞区人民路"));
//addressList.add(new AddressBean(153,"鑫纪外包厅","市区三部城郊二区","周炜	","株洲市荷塘区钻石路口"));
//addressList.add(new AddressBean(154,"株洲市石峰区精诚电子科技服务部","市区三部城郊二区","周炜	","响石广场"));
//addressList.add(new AddressBean(155,"石峰区聚点通讯专营店","市区三部城郊二区","周炜	","石峰区田心北门"));
//addressList.add(new AddressBean(156,"株洲市石峰区芳芳联通业务代办点","市区三部城郊二区","周炜	","石峰区建设北路果园小区"));
//addressList.add(new AddressBean(157,"戴树才","市区三部城郊二区","周炜	","湖南省株洲市石峰区云田镇云田乡五星村农贸市场一楼手机店"));
//addressList.add(new AddressBean(158,"株洲市荷塘区黄塘手机店","市区三部城郊二区","周炜	","株洲市荷塘区仙瘐镇黄塘商品街45号"));
//addressList.add(new AddressBean(159,"云龙示范区天成手机城","市区三部城郊二区","周炜	","株洲市石峰区云龙示范区林学院兴隆农贸市场天成手机城"));
//addressList.add(new AddressBean(160,"彭幼姣","市区三部城郊二区","周炜	","湖南省株洲市石峰区云田镇方特云龙沃店"));
//addressList.add(new AddressBean(161,"株洲市荷塘区联合通讯店","市区三部城郊二区","周炜	","株洲市荷塘区仙瘐镇黄塘商品街45号"));
//addressList.add(new AddressBean(162,"株洲市荷塘区丹文话费代收服务店","市区三部城郊二区","周炜	","湖南省株洲市荷塘区分路口茶园社区中国邮政代办点手机店"));
//addressList.add(new AddressBean(163,"荷塘区志良手机店","市区三部城郊二区","周炜	","湖南省株洲市荷塘区宋家桥430车辆厂正门中国联通营业厅（千金大药房隔壁）"));
//addressList.add(new AddressBean(164,"株洲市荷塘区晨曦通讯器材店","市区三部城郊二区","周炜	","湖南省株洲荷塘区戴家岭铁四院小区对面中国联通"));
//addressList.add(new AddressBean(165,"石峰区非凡通讯店","市区三部城郊二区","周炜	","湖南省株洲市石峰区云田乡马鞍村马步组马鞍山手机城"));
//addressList.add(new AddressBean(166,"荷塘区红鑫邮政代办点","市区三部城郊二区","周炜	","430车辆厂"));
//addressList.add(new AddressBean(167,"株洲市荷塘区树炼手机商店","市区三部城郊二区","周炜	","湖南省株洲市荷塘区仙庾振黄塘村聚豪酒店对面中国移动"));
//addressList.add(new AddressBean(168,"荷塘区明军通信行","市区三部城郊二区","周炜	","荷塘区明照乡分路口镇"));
//addressList.add(new AddressBean(169,"芦淞区桂林通讯商行","市区二部南区    ","郝鹏	","株洲市芦淞区市府房兴大厦临街1号"));
//addressList.add(new AddressBean(170,"谭本治","市区二部南区    ","郝鹏	","株洲市芦淞区建设南路23号"));
//addressList.add(new AddressBean(171,"芦淞区智成合赢通讯行","市区二部南区    ","郝鹏	","株洲市芦淞区芦淞路1053号"));
//addressList.add(new AddressBean(172,"株洲亲和力通讯贸易有限公司","市区二部南区    ","郝鹏	","株洲市芦淞区火车站旁邮政点"));
//addressList.add(new AddressBean(173,"湖南单明云商数码科技有限公司","市区二部南区    ","郝鹏	","株洲市芦淞区建设南路23号"));
//addressList.add(new AddressBean(174,"株洲市鸿鑫通讯","市区二部南区    ","郝鹏	","株洲市芦淞区火车站旁庆云广场"));
//addressList.add(new AddressBean(175,"芦淞区华俊通讯店","市区二部南区    ","郝鹏	","株洲市芦淞区株董路珉阁大厦118-1号门面"));
//addressList.add(new AddressBean(176,"株洲市芦淞区众汇通信产品经营部","市区二部南区    ","郝鹏	","株洲市芦淞区徐家桥步行街时代广场"));
//addressList.add(new AddressBean(177,"芦淞区新兄弟手机批发行","市区二部南区    ","郝鹏	","株洲市芦淞区徐家桥步行街1361号"));
//addressList.add(new AddressBean(178,"芦淞区雅睿通信行","市区二部南区    ","郝鹏	","株洲市芦淞区芦淞路1080号"));
//addressList.add(new AddressBean(179,"株洲市芦淞区兴达通信行","市区二部南区","郝鹏	","株洲市芦淞区建设南路徐家桥对面"));
//addressList.add(new AddressBean(180,"芦淞区王玲通信行","市区二部南区","郝鹏	","株洲火车站"));
//addressList.add(new AddressBean(181,"芦淞区雨鑫通信营业部","市区二部南区","郝鹏	","#N/A"));
//addressList.add(new AddressBean(182,"芦淞区大地鑫联外包厅","市区二部南区","郝鹏	","株洲市芦淞区大地内衣城对面"));
//addressList.add(new AddressBean(183,"芦淞区鑫联通信行","市区二部南区","郝鹏	","株洲市芦淞区徐家桥步行街对面"));
//addressList.add(new AddressBean(184,"芦淞区佳程人和通讯指定专营店","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼P1"));
//addressList.add(new AddressBean(185,"芦淞区联信通讯行","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼P3"));
//addressList.add(new AddressBean(186,"TZ株洲A南区恒达vivo专卖店（株洲市芦淞区恒达通信行）","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1797号（天域大酒店正对面联通营业厅）"));
//addressList.add(new AddressBean(187,"芦淞区新顺心通讯行","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼A9号"));
//addressList.add(new AddressBean(188,"株洲市芦淞区万和通讯行","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼P5号万和通讯"));
//addressList.add(new AddressBean(189,"株洲市芦淞区新盘龙通信产品批发部","市区二部佳诚区","陈忠亮	","株洲市芦淞区佳诚手机城旁新盘龙手机店"));
//addressList.add(new AddressBean(190,"株洲七空间网络科技有限公司","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼移动大厅"));
//addressList.add(new AddressBean(191,"芦淞区新鹏鑫通信行","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼p8柜"));
//addressList.add(new AddressBean(192,"向玉涵","市区二部佳诚区","陈忠亮	","株洲市芦淞区太子路1745号佳诚电脑手机市场一楼A15号"));
//addressList.add(new AddressBean(193,"株洲市荷塘区天域手机店","市区二部合泰    ","但银辉	","株洲市荷塘区东湖路裕丰三区1栋天域手机"));
//addressList.add(new AddressBean(194,"株洲市荷塘区合泰九州联通沃店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰大街10栋10号"));
//addressList.add(new AddressBean(195,"荷塘区翔龙通讯店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰裕丰广场三区翔龙通讯店"));
//addressList.add(new AddressBean(196,"株洲睿丞科技有限公司","市区二部合泰    ","但银辉	","株洲市荷塘区合泰大街50栋175号电信店"));
//addressList.add(new AddressBean(197,"株洲市荷塘区文文手机店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰大街五中路口41栋2号门面"));
//addressList.add(new AddressBean(198,"株洲市荷塘区万通移动通信指定专营店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰路609号移动门店"));
//addressList.add(new AddressBean(199,"荷塘区五中翔龙通讯店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰大街42栋门面五中翔龙店"));
//addressList.add(new AddressBean(200,"荷塘区亮亮通讯设备店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰街17栋102号"));
//addressList.add(new AddressBean(201,"株洲市荷塘区苑杰移动营业厅","市区二部合泰    ","但银辉	","株洲市荷塘区东湖路裕丰广场三区二栋"));
//addressList.add(new AddressBean(202,"株洲市荷塘区移动通信东湖专营店","市区二部合泰    ","但银辉	","株洲市荷塘区裕丰广场四区13栋中国移动门店"));
//addressList.add(new AddressBean(203,"株洲市荷塘区邓进通信产品店","市区二部合泰    ","但银辉	","株洲市荷塘区裕丰广场3区3栋中国移动门面"));
//addressList.add(new AddressBean(204,"中国移动通信铁西路指定专营店","市区二部合泰    ","但银辉	","株洲市芦淞区铁西路7号中国移动门面"));
//addressList.add(new AddressBean(205,"许吉亮","市区二部合泰    ","但银辉	","株洲市荷塘区合泰大街19号"));
//addressList.add(new AddressBean(206,"百家春超市（国讯通信）","市区二部合泰    ","但银辉	","株洲市荷塘区合泰大街与东湖路交汇处百家春超市移动店"));
//addressList.add(new AddressBean(207,"株洲市荷塘区合泰路天鹰通讯店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰路53栋1、2号门面"));
//addressList.add(new AddressBean(208,"荷塘区佳苑天若通信店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰银基小区15栋5号门面"));
//addressList.add(new AddressBean(209,"荷塘区武阳手机店","市区二部合泰    ","但银辉	","株洲市荷塘区文化路零零一连锁超市武阳手机店"));
//addressList.add(new AddressBean(210,"株洲市荷塘区雷雷科技有限公司","市区二部合泰    ","但银辉	","株洲市荷塘区裕丰广场4区雷雷科技"));
//addressList.add(new AddressBean(211,"荷塘区讯佳通讯店","市区二部合泰    ","但银辉	","株洲市荷塘区东湖路46号三区2栋1单元101号"));
//addressList.add(new AddressBean(212,"荷塘区友谊手机店","市区二部合泰    ","但银辉	","荷塘区合泰路460号"));
//addressList.add(new AddressBean(213,"株洲市荷塘区雄哥手机店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰文化路"));
//addressList.add(new AddressBean(214,"株洲市荷塘区万鑫手机店","市区二部合泰    ","但银辉	","株洲市荷塘区合泰裕丰路商住楼103.104门面"));
//addressList.add(new AddressBean(215,"株洲市荷塘区宇天移动营业厅","市区二部合泰    ","但银辉	","株洲市荷塘区文化路晨光小区"));
//addressList.add(new AddressBean(216,"荷塘区联通裕丰专营店","市区二部合泰    ","但银辉	","株洲市荷塘区裕丰广场一区一栋裕丰沃店"));
//addressList.add(new AddressBean(217,"荷塘区联通裕丰专营店（二店）","市区二部合泰    ","但银辉	","荷塘区荷塘铺村富家垅组散户"));
//addressList.add(new AddressBean(218,"株洲市荷塘区东湖电信代理店","市区二部城郊区","叶少华	","株洲市荷塘区东湖路裕丰广场4区11栋"));
//addressList.add(new AddressBean(219,"株洲市荷塘区金富小区移动专营店","市区二部城郊区","叶少华	","株洲市荷塘区财富小区"));
//addressList.add(new AddressBean(220,"荷塘区辉旭沃店","市区二部城郊区","叶少华	","株洲市荷塘区财富小区"));
//addressList.add(new AddressBean(221,"新世纪通讯","市区二部城郊区","叶少华	","株洲市荷塘区富家垅A区029栋"));
//addressList.add(new AddressBean(222,"株洲市荷塘区移动敏讯指定专营店","市区二部城郊区","叶少华	","株洲市荷塘区富家垅敏讯店"));
//addressList.add(new AddressBean(223,"株洲市荷塘区治军通讯店","市区二部城郊区","叶少华	","株洲市荷塘区富家垅散户1幢1号"));
//addressList.add(new AddressBean(224,"株洲市荷塘区天仁移动指定专营店","市区二部城郊区","叶少华	","株洲市芦淞区石宋路财富小区内"));
//addressList.add(new AddressBean(225,"荷塘区瑞兰通讯行","市区二部城郊区","叶少华	","株洲市荷塘区合泰路"));
//addressList.add(new AddressBean(226,"株洲市芦淞区南方科大业务经营部","市区二部城郊区","叶少华	","株洲市芦淞区董家塅迎新街18号南方营业厅"));
//addressList.add(new AddressBean(227,"芦淞区中为通讯店","市区二部城郊区","叶少华	","株洲市芦淞区曼哈顿商业广场104号"));
//addressList.add(new AddressBean(228,"株洲市微沃电子科技有限公司","市区二部城郊区","叶少华	","株洲市芦淞区宇般路36号航怡园地下室104号中国联通门面"));
//addressList.add(new AddressBean(229,"芦淞区联盛通讯行","市区二部城郊区","叶少华	","株洲市芦淞区摩托车大市场锦云摩配城51-1"));
//addressList.add(new AddressBean(230,"芦淞区智天手机店","市区二部城郊区","叶少华	","株洲市芦淞区芦淞路226号奇迹超市内"));
//addressList.add(new AddressBean(231,"芦淞区肖华龙通信专营店","市区二部城郊区","叶少华	","株洲市芦淞区芦淞路295号老百姓大药房对面中国移动"));
//addressList.add(new AddressBean(232,"芦淞区姐妹通讯行","市区二部城郊区","叶少华	","株洲市芦淞区高家坳楠竹小区旁中国移动"));
//addressList.add(new AddressBean(233,"芦淞区华讯通讯行","市区二部城郊区","叶少华	","株洲市芦淞区曼哈顿商业广场141-142号门面"));
//addressList.add(new AddressBean(234,"芦淞区世通电信芦淞路代理店","市区二部城郊区","叶少华	","株洲市芦淞区芦淞路108号"));
//addressList.add(new AddressBean(235,"芦淞区宋友明电信业务代办点","市区二部城郊区","叶少华	","株洲市芦淞区芦淞工业园1栋5号门面中国电信"));
//addressList.add(new AddressBean(236,"芦淞区世纪通讯行","市区二部城郊区","叶少华	","株洲市芦淞区新芦淞工业园10栋一楼3号门面"));
//addressList.add(new AddressBean(237,"芦淞区钱仁军通讯店","市区二部城郊区","叶少华	","株洲市芦淞区芦淞工业园"));
//addressList.add(new AddressBean(238,"芦淞区联众通讯行","市区二部城郊区","叶少华	","株洲市芦淞区工业园32栋8号中国联通"));
//addressList.add(new AddressBean(239,"芦淞区细洪手机店","市区二部城郊区","叶少华	","株洲市荷塘区工业园1栋1号门店"));
//addressList.add(new AddressBean(240,"芦淞区陈静宇通讯行","市区二部城郊区","叶少华	","株洲市芦淞区百江明珠21栋负一楼百顺购物门口电信专柜"));
//addressList.add(new AddressBean(241,"株洲市石峰区玉林移动代办点","市区二部北区 ","肖冬立	","株洲市石峰区清石广场邮政局旁"));
//addressList.add(new AddressBean(242,"株洲市石峰区湘天桥移动特约代理店","市区二部北区 ","肖冬立	","株洲市石峰区清石广场广汇大厦一楼移动营业厅1号门面"));
//addressList.add(new AddressBean(243,"株洲市石峰区强强清水塘电信专营店","市区二部北区 ","肖冬立	","株洲市石峰区清水塘邮政局旁电信营业厅"));
//addressList.add(new AddressBean(244,"石峰区佳音联通清石专营店","市区二部北区 ","肖冬立	","株洲市石峰区清石广场中国联通25门面"));
//addressList.add(new AddressBean(245,"株洲市石峰区鲜云手机商店","市区二部北区 ","肖冬立	","株洲市石峰区湘天桥380号惠特旁联通门店"));
//addressList.add(new AddressBean(246,"中国联合网络通信有限公司株洲市分公司石峰怡心花园营业厅","市区二部北区 ","肖冬立	","株洲市石峰区天桥街"));
//addressList.add(new AddressBean(247,"株洲市石峰区乐天通讯业务经营部","市区二部北区 ","肖冬立	","株洲市石峰区株百超市旁移动门店"));
//addressList.add(new AddressBean(248,"株洲市石峰区敏捷通讯经营部","市区二部北区 ","肖冬立	","株洲市石峰区建设北路杉木塘天桥旁移动营业厅"));
//addressList.add(new AddressBean(249,"株洲市石峰区响石岭湘渌手机店","市区二部北区 ","肖冬立	","株洲市石峰区响石广场湘渌酒店旁移动门店"));
//addressList.add(new AddressBean(250,"石峰区响石自营瑞鑫外包柜","市区二部北区 ","肖冬立	","株洲市石峰区石峰株百旁联通门店"));
//addressList.add(new AddressBean(251,"株洲市石峰区百诺手机专卖店","市区二部北区 ","肖冬立	","株洲市石峰区钢厂福临阁百诺手机专卖店"));
//addressList.add(new AddressBean(252,"渗透手机卖场","市区二部北区 ","肖冬立	","株洲市石峰区杉木塘步步高里面"));
//addressList.add(new AddressBean(253,"株洲市荷塘区天翼手机卖场财富店","市区二部城郊二一区","0	","财富小区2栋101门面"));
//addressList.add(new AddressBean(254,"集团客户联通-株洲A","0","0	","株洲市芦淞区建设南路108号家润多A座1006室"));
//addressList.add(new AddressBean(255,"集团客户电信-株洲A","0","0	","株洲市芦淞区建设南路108号家润多A座1006室"));
//addressList.add(new AddressBean(256,"集团客户移动-株洲A","0","0	","株洲市芦淞区建设南路108号家润多A座1006室"));
//
//
//
//
//    }

    public static void init() {

    }
}
